var _importDefault = (this && this._importDefault) || function (mod) {
    return (mod && mod._esModule) ? mod : { "default": mod };
};
define(["require", "exports", "N/search"], function (require, exports, search_1) {
    "use strict";
    Object.defineProperty(exports, "_esModule", { value: true });
    exports.buttonsSl = exports.sublistPopulateFields = exports.sublistFields = exports.searchFilters = exports.tipoProduto = exports.statusProdutoOpts = exports.classificacaoOpts = exports.areaDeNegocioOpts = exports.tipoPessoaOpts = exports.searchColumnsModApi = exports.searchColumnsModWeb = exports.searchColumnsNomeProduto = exports.searchColumnsItens = exports.searchColumnsItens2 = exports.fieldsModApiRec = exports.fieldsNModWebRec = exports.fieldsNomeProdutoRec = exports.fieldsItemRec = exports.itemColumns = void 0;
    search_1 = _importDefault(search_1);
    exports.itemColumns = [
        { name: "externalid", label: "ID Externo" },
        { name: "itemid", label: "Nome" },
        { name: "custitemcustitem_field_nome_prod", label: "Nome do Produto" },
        { name: "custitem_sku", label: "SKU" },
        { name: "custitem_item_nome_amigavel", label: "Nome amigável" },
        { name: "displayname", label: "Nome de exibição (traduzido" },
        { name: "salesdescription", label: "Descrição" },
        { name: "formulatext", formula: " {isinactive}", label: "Inativo" },
        { name: "custitem_field_area_negocio", label: "Área de negócio" },
        { name: "custitem_field_tipo_prod", label: "Tipo do produto" },
        { name: "custitem_field_tipo_pessoa", label: "Tipo Pessoa" },
        { name: "custitem_field_classif_prod", label: "Classificação do Produto" },
        { name: "custitem_status_produto", label: "Status Produto" },
        { name: "custitem_margem_receita", label: "Margem Receita" },
        { name: "custitem_impostos_receita", label: "Impostos Receita" },
        { name: "custitem_metodo_de_tarifacao", label: "Método de Tarifação" },
        { name: "formulatext", formula: "{custitem_flag_backtest}", label: "Backtest	" },
        { name: "formulatext", formula: "{custitem_clausula_contrat_espec}", label: "Cláusula Contratual Específica" },
        { name: "department", label: "Departamento" },
        { name: "custitem_familia_produto", label: " Família de Produtos" },
        { name: "location", label: "Localidade" },
        { name: "subsidiary", label: "Subsidiária" },
        { name: "formulatext", formula: "{includechildren} ", label: "Incluir filhos" },
        { name: "custitem_access_web", label: "Controla Acesso via Web" },
        { name: "custitem_access_api", label: "Controla Acesso via API" },
        { name: "custitem_access_batch", label: "Controla Acesso via Bacth" },
        { name: "custitem_selecionar_modulo", label: "Selecionar Módulo Web" },
        { name: "formulatext", formula: "{custitem_mbs_acesso_posivo}", label: "MBS Acesso ao Positivo" },
        { name: "custitem_pix_codigo", label: "Código PIX" },
        { name: "custitem_pix_tipo_servico", label: "Tipo de serviço " },
        { name: "custitem_item_subtype", label: "Subtipo de Item" },
        { name: "custitem_acs_item_type_ls", label: "Tipo" },
        { name: "custitem_billing", label: "Controle de Bilhetagem" },
        { name: "custitem_tipo_receita", label: "Tipo de Receita" },
        { name: "custitem_item_no_hit", label: "Produto No Hit" },
        { name: "custitem_qtd_pacote", label: "Quantidade do Pacote" },
        { name: "custitem_tipo_batch_negativacao", label: "Registro Batch Negativação" },
        { name: "custitem_batch_controlcred_op", label: "Operação Batch Controlcred" },
        { name: "custitem_itens_upgrade", label: "Itens Upgrade" },
        { name: "custitem_itens_downgrade", label: "Itens Downgrade" },
        { name: "formulatext", formula: "{custitem_item_novoprocesso}", label: "Novo Processo de Compras" },
        { name: "custitem_periodicidade", label: "Periodicidade do Produto" },
        { name: "custitem_cupom_desc_canc_pme", label: "Cupom de desconto cancelamento PME" },
        { name: "custitem_cod_reg_batch", label: "Código Registro Batch" },
        { name: "custitem_canal_comunicacao", label: "Canal de Comunicação" },
        { name: "custitemcustitem_prod_sem_desc_pr", label: "Item Padrão Vinculado (Sem Descontos" },
        { name: "formulatext", formula: "{custitem_item_vcm_global}", label: "Item de VCM Global" },
        { name: "custitem_numero_logins", label: "Número de logins por plano" },
        { name: "custitem_acs_item_tipo_produto", label: "Tipo de Produto" },
        { name: "custitem_selecionar_modulo_apimbs", label: "Selecionar Módulo API" }
    ];
    exports.fieldsItemRec = [
        "externalid",
        "itemid",
        "custitemcustitem_field_nome_prod",
        "custitem_item_nome_amigavel",
        "displayname",
        "salesdescription",
        "isinactive",
        "custitem_field_area_negocio",
        "custitem_field_tipo_prod",
        "custitem_field_tipo_pessoa",
        "custitem_field_classif_prod",
        "custitem_status_produto",
        "custitem_margem_receita",
        "custitem_impostos_receita",
        "custitem_metodo_de_tarifacao",
        "custitem_flag_backtest",
        "custitem_clausula_contrat_espec",
        "department",
        "custitem_familia_produto",
        "location",
        "subsidiary",
        "includechildren",
        "custitem_access_web",
        "custitem_access_api",
        "custitem_access_batch",
        "custitem_selecionar_modulo",
        "custitem_mbs_acesso_posivo",
        "custitem_pix_codigo",
        "custitem_pix_tipo_servico",
        "custitem_item_subtype",
        "custitem_acs_item_type_ls",
        "custitem_billing",
        "custitem_tipo_receita",
        "custitem_item_no_hit",
        "custitem_qtd_pacote",
        "custitem_tipo_batch_negativacao",
        "custitem_batch_controlcred_op",
        "custitem_itens_upgrade",
        "custitem_itens_downgrade",
        "custitem_item_novoprocesso",
        "custitem_periodicidade",
        "custitem_cupom_desc_canc_pme",
        "custitem_cod_reg_batch",
        "custitem_canal_comunicacao",
        "custitemcustitem_prod_sem_desc_pr",
        "custitem_item_vcm_global",
        "custitem_numero_logins",
        "custitem_acs_item_tipo_produto",
        "custitem_selecionar_modulo_apimbs"
    ];
    exports.fieldsNomeProdutoRec = [
        "name",
        "custrecord_nome_produto",
    ];
    exports.fieldsNModWebRec = [
        "name",
        "custrecord_codigo_produto_mbs",
        "custrecord_quoid_role_mbs",
    ];
    exports.fieldsModApiRec = [
        "name",
        "custrecord_produto_mbs",
        "custrecord_role_mbs",
    ];
    exports.searchColumnsItens2 = [
        "externalid",
        "itemid",
        "custitemcustitem_field_nome_prod",
        "custitemcustitem_field_nome_prod.name",
        "custitemcustitem_field_nome_prod.custrecord_nome_produto",
        "custitem_sku",
        "custitem_item_nome_amigavel",
        "displayname",
        "salesdescription",
        "isinactive",
        "custitem_field_area_negocio",
        "custitem_field_tipo_prod",
        "custitem_field_tipo_pessoa",
        "custitem_field_classif_prod",
        "custitem_status_produto",
        "custitem_margem_receita",
        "custitem_impostos_receita",
        "custitem_metodo_de_tarifacao",
        "custitem_flag_backtest",
        "custitem_clausula_contrat_espec",
        "department",
        "custitem_familia_produto",
        "location",
        "subsidiary",
        "includechildren",
        "custitem_access_web",
        "custitem_access_api",
        "custitem_access_batch",
        "custitem_selecionar_modulo",
        "custitem_selecionar_modulo.name",
        //"custitem_selecionar_modulo.parent",
        "custitem_selecionar_modulo.custrecord_codigo_produto_mbs",
        "custitem_selecionar_modulo.custrecord_quoid_role_mbs",
        "custitem_mbs_acesso_posivo",
        "custitem_pix_codigo",
        "custitem_pix_tipo_servico",
        "custitem_item_subtype",
        "custitem_acs_item_type_ls",
        "custitem_billing",
        "custitem_tipo_receita",
        "custitem_item_no_hit",
        "custitem_qtd_pacote",
        "custitem_tipo_batch_negativacao",
        "custitem_batch_controlcred_op",
        "custitem_itens_upgrade",
        "custitem_itens_downgrade",
        "custitem_item_novoprocesso",
        "custitem_periodicidade",
        "custitem_cupom_desc_canc_pme",
        "custitem_cod_reg_batch",
        "custitem_canal_comunicacao",
        "custitemcustitem_prod_sem_desc_pr",
        "custitem_item_vcm_global",
        "custitem_numero_logins",
        "custitem_acs_item_tipo_produto",
        "custitem_selecionar_modulo_apimbs",
        "custitem_selecionar_modulo_apimbs.name",
        //"custitem_selecionar_modulo_apimbs.parent",
        "custitem_selecionar_modulo_apimbs.custrecord_produto_mbs",
        "custitem_selecionar_modulo_apimbs.custrecord_role_mbs",
    ];
    exports.searchColumnsItens = [
        search_1.createColumn({ name: "externalid", label: "ID Externo" }),
        search_1.createColumn({ name: "itemid", label: "Nome" }),
        //Campos Nome Produto - início
        search_1.createColumn({ name: "custitemcustitem_field_nome_prod" }),
        search_1.createColumn({ name: "name", join: "custitemcustitem_field_nome_prod" }),
        search_1.createColumn({ name: "custrecord_nome_produto", join: "custitemcustitem_field_nome_prod" }),
        //Campos Nome Produto - fim
        search_1.createColumn({ name: "custitem_sku", label: "SKU" }),
        search_1.createColumn({ name: "custitem_item_nome_amigavel", label: "Nome amigável" }),
        search_1.createColumn({ name: "displayname", label: "Nome de exibição (traduzido)" }),
        search_1.createColumn({ name: "salesdescription", label: "Descrição" }),
        search_1.createColumn({ name: "formulatext", formula: " {isinactive}", label: "Inativo" }),
        search_1.createColumn({ name: "custitem_field_area_negocio", label: "Área de negócio" }),
        search_1.createColumn({ name: "custitem_field_tipo_prod", label: "Tipo do produto" }),
        search_1.createColumn({ name: "custitem_field_tipo_pessoa", label: "Tipo Pessoa" }),
        search_1.createColumn({ name: "custitem_field_classif_prod", label: "Classificação do Produto" }),
        search_1.createColumn({ name: "custitem_status_produto", label: "Status Produto" }),
        search_1.createColumn({ name: "custitem_margem_receita", label: "Margem Receita" }),
        search_1.createColumn({ name: "custitem_impostos_receita", label: "Impostos Receita" }),
        search_1.createColumn({ name: "custitem_metodo_de_tarifacao", label: "Método de Tarifação" }),
        search_1.createColumn({ name: "formulatext", formula: "{custitem_flag_backtest}", label: "Backtest	" }),
        search_1.createColumn({ name: "formulatext", formula: "{custitem_clausula_contrat_espec}", label: "Cláusula Contratual Específica" }),
        search_1.createColumn({ name: "department", label: "Departamento" }),
        search_1.createColumn({ name: "custitem_familia_produto", label: " Família de Produtos" }),
        search_1.createColumn({ name: "location", label: "Localidade" }),
        search_1.createColumn({ name: "subsidiary", label: "Subsidiária" }),
        search_1.createColumn({ name: "formulatext", formula: "{includechildren} ", label: "Incluir filhos" }),
        search_1.createColumn({ name: "custitem_access_web", label: "Controla Acesso via Web" }),
        search_1.createColumn({ name: "custitem_access_api", label: "Controla Acesso via API" }),
        search_1.createColumn({ name: "custitem_access_batch", label: "Controla Acesso via Bacth" }),
        //Campos SELECIONAR MÓDULO WEB - início
        //nsr.createColumn({ name: "id", join: "custitem_selecionar_modulo"}),
        search_1.createColumn({ name: "custitem_selecionar_modulo" }),
        search_1.createColumn({ name: "name", join: "custitem_selecionar_modulo" }),
        //nsr.createColumn({ name: "parent", join: "custitem_selecionar_modulo" }),
        search_1.createColumn({ name: "custrecord_codigo_produto_mbs", join: "custitem_selecionar_modulo" }),
        search_1.createColumn({ name: "custrecord_quoid_role_mbs", join: "custitem_selecionar_modulo" }),
        //Campos SELECIONAR MÓDULO WEB - início
        search_1.createColumn({ name: "formulatext", formula: "{custitem_mbs_acesso_posivo}", label: "MBS Acesso ao Positivo" }),
        search_1.createColumn({ name: "custitem_pix_codigo", label: "Código PIX" }),
        search_1.createColumn({ name: "custitem_pix_tipo_servico", label: "Tipo de serviço " }),
        search_1.createColumn({ name: "custitem_item_subtype", label: "Subtipo de Item" }),
        search_1.createColumn({ name: "custitem_acs_item_type_ls", label: "Tipo" }),
        search_1.createColumn({ name: "custitem_billing", label: "Controle de Bilhetagem" }),
        search_1.createColumn({ name: "custitem_tipo_receita", label: "Tipo de Receita" }),
        search_1.createColumn({ name: "custitem_item_no_hit", label: "Produto No Hit" }),
        search_1.createColumn({ name: "custitem_qtd_pacote", label: "Quantidade do Pacote" }),
        search_1.createColumn({ name: "custitem_tipo_batch_negativacao", label: "Registro Batch Negativação" }),
        search_1.createColumn({ name: "custitem_batch_controlcred_op", label: "Operação Batch Controlcred" }),
        search_1.createColumn({ name: "custitem_itens_upgrade", label: "Itens Upgrade" }),
        search_1.createColumn({ name: "custitem_itens_downgrade", label: "Itens Downgrade" }),
        search_1.createColumn({ name: "formulatext", formula: "{custitem_item_novoprocesso}", label: "Novo Processo de Compras" }),
        search_1.createColumn({ name: "custitem_periodicidade", label: "Periodicidade do Produto" }),
        search_1.createColumn({ name: "custitem_cupom_desc_canc_pme", label: "Cupom de desconto cancelamento PME" }),
        search_1.createColumn({ name: "custitem_cod_reg_batch", label: "Código Registro Batch" }),
        search_1.createColumn({ name: "custitem_canal_comunicacao", label: "Canal de Comunicação" }),
        search_1.createColumn({ name: "custitemcustitem_prod_sem_desc_pr", label: "Item Padrão Vinculado (Sem Descontos)" }),
        search_1.createColumn({ name: "formulatext", formula: "{custitem_item_vcm_global}", label: "Item de VCM Global" }),
        search_1.createColumn({ name: "custitem_numero_logins", label: "Número de logins por plano" }),
        search_1.createColumn({ name: "custitem_acs_item_tipo_produto", label: "Tipo de Produto" }),
        //Campos SELECIONAR MÓDULO API - início
        search_1.createColumn({ name: "custitem_selecionar_modulo_apimbs" }),
        //nsr.createColumn({ name: "parent", join: "custitem_selecionar_modulo_apimbs" }),
        search_1.createColumn({ name: "custrecord_produto_mbs", join: "custitem_selecionar_modulo_apimbs" }),
        search_1.createColumn({ name: "custrecord_role_mbs", join: "custitem_selecionar_modulo_apimbs" }),
        //Campos SELECIONAR MÓDULO API - início
    ];
    exports.searchColumnsNomeProduto = [
        search_1.createColumn({ name: "name", sort: search_1.Sort.ASC }),
        //nsr.createColumn({ name: "parent" }),
        search_1.createColumn({ name: "custrecord_nome_produto" }),
    ];
    exports.searchColumnsModWeb = [
        search_1.createColumn({ name: "name", sort: search_1.Sort.ASC }),
        //nsr.createColumn({ name: "parent" }),
        search_1.createColumn({ name: "custrecord_codigo_produto_mbs" }),
        search_1.createColumn({ name: "custrecord_quoid_role_mbs" }),
    ];
    exports.searchColumnsModApi = [
        search_1.createColumn({ name: "name", sort: search_1.Sort.ASC }),
        //nsr.createColumn({ name: "parent" }),
        search_1.createColumn({ name: "custrecord_produto_mbs" }),
        search_1.createColumn({ name: "custrecord_role_mbs" }),
    ];
    exports.tipoPessoaOpts = [
        { value: "@NONE@", text: "-Nenhum-" },
        { value: 1, text: "PF" },
        { value: 2, text: "PJ" },
        { value: 3, text: "PF/PJ" }
    ];
    exports.areaDeNegocioOpts = [
        { value: "", text: "-Nenhum-" },
        { value: 1, text: "Crédito" },
        { value: 2, text: "Cobrança" },
        { value: 3, text: "Compliance" },
        { value: 4, text: "Fraude" },
        { value: 5, text: "CRM" }
    ];
    exports.classificacaoOpts = [
        { value: "", text: "-Nenhum-" },
        { value: 1, text: "Hub de dados" },
        { value: 2, text: "Plataformas" },
        { value: 3, text: "Relatório de Crédito" },
        { value: 4, text: "Serviços de Negativação" },
        { value: 5, text: "Soluções Analíticas" },
        { value: 6, text: "Atributos" }
    ];
    exports.statusProdutoOpts = [
        { value: "", text: "-Nenhum-" },
        { value: 1, text: "MVP" },
        { value: 2, text: "Pontual" },
        { value: 3, text: "Produtivo" }
    ];
    exports.tipoProduto = [
        { value: "", text: "-Nenhum-" },
        { value: 1, text: "Customizado" },
        { value: 2, text: "Customizado Parceiro" },
        { value: 3, text: "Parceiro" },
        { value: 4, text: "Prateleira" }
    ];
    exports.searchFilters = {
        "filterItens": [["type", "anyof", "Service"], "AND", ["subtype", "anyof", "Sale"]]
    };
    exports.sublistFields = [
        { id: 'select_item', type: "CHECKBOX", label: 'Selecionar' },
        { id: 'id', type: "TEXT", label: 'Internal ID' },
        { id: 'itemid', type: "TEXT", label: 'Item Name' },
        { id: 'custitemcustitem_field_nome_prod', type: "TEXT", label: 'Nome do Produto' },
        { id: 'sku', type: "TEXT", label: 'Item SKU' },
        { id: 'custitem_item_nome_amigavel', type: "TEXT", label: 'Nome amigável' },
        { id: 'displayname', type: "TEXT", label: 'Nome de exibição (traduzido)' },
        { id: 'salesdescription', type: "TEXT", label: 'Descrição' },
        { id: 'custitem_field_area_negocio', type: "TEXT", label: 'Área de negócio' },
        { id: 'custitem_field_tipo_prod', type: "TEXT", label: 'Tipo do produto' },
        { id: 'custitem_field_tipo_pessoa', type: "TEXT", label: 'Tipo Pessoa' },
        { id: 'custitem_field_classif_prod', type: "TEXT", label: 'Classificação do Produto' },
        { id: 'custitem_status_produto', type: "TEXT", label: 'Status Produto' },
        { id: 'custitem_margem_receita', type: "TEXT", label: 'Margem Receita' },
        { id: 'custitem_metodo_de_tarifacao', type: "TEXT", label: 'Método de Tarifação' },
        { id: 'department', type: "TEXT", label: 'Departamento' },
        { id: 'custitem_familia_produto', type: "TEXT", label: ' Família de Produtos' },
        { id: 'location', type: "TEXT", label: 'Localidade' },
        { id: 'subsidiary', type: "TEXT", label: 'Subsidiária' },
        { id: 'custitem_access_web', type: "TEXT", label: 'Controla Acesso via Web' },
        { id: 'custitem_access_api', type: "TEXT", label: 'Controla Acesso via API' },
        { id: 'custitem_access_batch', type: "TEXT", label: 'Controla Acesso via Bacth' },
        { id: 'custitem_selecionar_modulo', type: "TEXT", label: 'Selecionar Módulo Web' },
        { id: 'custitem_pix_codigo', type: "TEXT", label: 'Código PIX' },
        { id: 'custitem_pix_tipo_servico', type: "TEXT", label: 'Tipo de serviço' },
        { id: 'custitem_item_subtype', type: "TEXT", label: 'Subtipo de Item' },
        { id: 'custitem_acs_item_type_ls', type: "TEXT", label: 'Tipo' },
        { id: 'custitem_billing', type: "TEXT", label: 'Controle de Bilhetagem' },
        { id: 'custitem_tipo_receita', type: "TEXT", label: 'Tipo de Receita' },
        { id: 'custitem_item_no_hit', type: "TEXT", label: 'Produto No Hit' },
        { id: 'custitem_qtd_pacote', type: "TEXT", label: 'Quantidade do Pacote' },
        { id: 'custitem_tipo_batch_negativacao', type: "TEXT", label: 'Registro Batch Negativação' },
        { id: 'custitem_batch_controlcred_op', type: "TEXT", label: 'Operação Batch Controlcred' },
        { id: 'custitem_itens_upgrade', type: "TEXT", label: 'Itens Upgrade' },
        { id: 'custitem_itens_downgrade', type: "TEXT", label: 'Itens Downgrade' },
        { id: 'custitem_periodicidade', type: "TEXT", label: 'Periodicidade do Produto' },
        { id: 'custitem_cupom_desc_canc_pme', type: "TEXT", label: 'Cupom de desconto cancelamento PME' },
        { id: 'custitem_cod_reg_batch', type: "TEXT", label: 'Código Registro Batch' },
        { id: 'custitem_canal_comunicacao', type: "TEXT", label: 'Canal de Comunicação' },
        { id: 'custitemcustitem_prod_sem_desc_pr', type: "TEXT", label: 'Item Padrão Vinculado (Sem Descontos)' },
        { id: 'custitem_numero_logins', type: "TEXT", label: 'Número de logins por plano' },
        { id: 'custitem_acs_item_tipo_produto', type: "TEXT", label: 'Tipo de Produto' },
        { id: 'custitem_selecionar_modulo_apimbs', type: "TEXT", label: 'Selecionar Módulo API' },
        { id: 'rec_fields', type: 'TEXTAREA', label: 'Rec. Campos' }
    ];
    exports.sublistPopulateFields = [
        // { id: 'select_item', type: "CHECKBOX", label: 'Selecionar' },
        { id: 'id', type: "id" },
        { id: 'itemid', type: "getValue" },
        { id: 'custitemcustitem_field_nome_prod', type: "getText" },
        { id: 'sku', type: "sku" },
        { id: 'custitem_item_nome_amigavel', type: "getValue" },
        { id: 'displayname', type: "getValue" },
        { id: 'salesdescription', type: "getValue" },
        { id: 'custitem_field_area_negocio', type: "getText" },
        { id: 'custitem_field_tipo_prod', type: "getText" },
        { id: 'custitem_field_tipo_pessoa', type: "getText" },
        { id: 'custitem_field_classif_prod', type: "getText" },
        { id: 'custitem_status_produto', type: "getText" },
        { id: 'custitem_margem_receita', type: "getValue" },
        { id: 'custitem_metodo_de_tarifacao', type: "getText" },
        { id: 'department', type: "getText" },
        { id: 'custitem_familia_produto', type: "getText" },
        { id: 'location', type: "getText" },
        { id: 'subsidiary', type: "getText" },
        { id: 'custitem_access_web', type: "getText" },
        { id: 'custitem_access_api', type: "getText" },
        { id: 'custitem_access_batch', type: "getText" },
        { id: 'custitem_selecionar_modulo', type: "getValue" },
        { id: 'custitem_pix_codigo', type: "getText" },
        { id: 'custitem_pix_tipo_servico', type: "getText" },
        { id: 'custitem_item_subtype', type: "getText" },
        { id: 'custitem_acs_item_type_ls', type: "getText" },
        { id: 'custitem_billing', type: "getText" },
        { id: 'custitem_tipo_receita', type: "getText" },
        { id: 'custitem_item_no_hit', type: "getText" },
        { id: 'custitem_qtd_pacote', type: "getText" },
        { id: 'custitem_tipo_batch_negativacao', type: "getValue" },
        { id: 'custitem_batch_controlcred_op', type: "getValue" },
        { id: 'custitem_itens_upgrade', type: "getText" },
        { id: 'custitem_itens_downgrade', type: "getText" },
        { id: 'custitem_periodicidade', type: "getText" },
        { id: 'custitem_cupom_desc_canc_pme', type: "getText" },
        { id: 'custitem_cod_reg_batch', type: "getText" },
        { id: 'custitem_canal_comunicacao', type: "getText" },
        { id: 'custitemcustitem_prod_sem_desc_pr', type: "getText" },
        { id: 'custitem_numero_logins', type: "getText" },
        { id: 'custitem_acs_item_tipo_produto', type: "getText" },
        { id: 'custitem_selecionar_modulo_apimbs', type: "getText" },
        { id: 'rec_fields', type: 'rec_fields' }
    ];
    exports.buttonsSl = [
        { label: "Enviar itens", id: "custpage_check_sb1_rl", functionName: "sendItemListRl" },
        { label: "Limpar lista de itens", id: "custpage_clean_sbl", functionName: "cleanSublist" },
        { label: "Filtrar", id: "custpage_apply_filter", functionName: "applyFilters" }
    ];
});
